# render.yaml
# Definitive blueprint for deploying the IT Asset Manager on Render.
# This version uses the correct, separate 'databases' and 'services' blocks
# as per the official Render documentation.

# 1. The PostgreSQL Database
# This dedicated block is the standard way to define a database.
databases:
  - name: asset-manager-db
    region: oregon # Recommended to set a region for better performance

# 2. The Web Service
# The 'services' block is for non-database services like our Flask app.
services:
  - type: web
    name: it-asset-manager
    region: oregon # Must match the database region
    env: python
    branch: 67-deploy-the-application
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn 'asset_manager:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        # This securely gets the URL from the database defined above.
        fromDatabase:
          name: asset-manager-db # This MUST match the database name above.
          property: internalUrl
