# .github/workflows/python-tests.yml

# This is the name of your workflow. It will appear in the "Actions" tab of your GitHub repository.
name: Python Application Tests

# This section defines when the workflow will run.
on:
  # Run on every push to the 'main' branch.
  push:
    branches: [ "main" ]
  # Also run on every pull request that targets the 'main' or 'master' branch.
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a common, reliable choice.
    runs-on: ubuntu-latest

    # A job is a sequence of steps.
    steps:
      # Step 1: Check out your repository's code
      # This is a standard action that downloads your code into the runner so the job can access it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up a Python environment
      # This action installs a specific version of Python on the runner.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # You can change this to match your project's Python version.

      # Step 3: Install project dependencies
      # This step executes command-line commands.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Step 4: Run the tests with pytest
      # This command executes your entire test suite. If any test fails, this step will fail,
      # and the entire workflow run will be marked as failed.
      - name: Run tests
        run: |
          pytest
